- hosts: tomcat
  become: yes
  tasks:
    - name: 'Deploy Java Build in Tomcat server'
      copy:
        dest: '/opt/tomcat10/webapps/webapp.war/'
        src: '../calculator-app/target/calculator-1.0.0.war'
        mode: 0755

    - name: 'Restart Tomcat server'
      service:
        name: 'tomcat'
        state: restarted
