---
- name: Install and deploy Tomcat-9.0.75
  hosts: tomcat
  become: yes
  
  tasks:
    - name: Download Open JDK
      become: yes

      apt:
        name: default-jdk
        update_cache: yes
        state: present

    - name: Validate if Java is available
      shell: java -version

    - name: Create the group
      become: yes
      group:
        name: tomcat
        state: present

    - name: Create the user
      become: yes
      user:
        name: tomcat
        state: present

    - name: Create a directory /opt/tomcat
      become: yes
      file:
        path: /opt/tomcat
        state: directory
        mode: 


        owner: tomcat
        group: tomcat

    - name: Download Tomcat archive
      become: yes
      get_url:
        url: " https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.75/bin/apache-tomcat-9.0.75.tar.gz"
        dest: /opt/tomcat/apache-tomcat-9.0.75.tar.gz
       
    - name: Extract Tomcat archive
      become: yes
      ansible.builtin.unarchive:
        src: /opt/tomcat/apache-tomcat-9.0.75.tar.gz
        dest: /opt/tomcat
        remote_src: yes
        extra_opts: [--strip-components=1]      

    - name: Reload the SystemD to re-read configurations
      become: yes
      systemd:
        daemon_reload: yes

    - name: Create Tomcat service file
      template:
        src: service/tomcat.service
        dest: /etc/systemd/system/tomcat.service

    - name: Reload systemd config
      systemd:
        daemon_reload: yes

    - name: Enable and start Tomcat service
      service:
        name: tomcat
        state: started
        enabled: yes
